# schema.yml

version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        config:
          alias: sales
      - name: raw_gz_product
        config:
          alias: product
      - name: raw_gz_ship
        config:
          alias: ship